/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/CompressedImage.proto */

#ifndef PROTOBUF_C_foxglove_2fCompressedImage_2eproto__INCLUDED
#define PROTOBUF_C_foxglove_2fCompressedImage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"

typedef struct Foxglove__CompressedImage Foxglove__CompressedImage;


/* --- enums --- */


/* --- messages --- */

/*
 * A compressed image
 */
struct  Foxglove__CompressedImage
{
  ProtobufCMessage base;
  /*
   * Timestamp of image
   */
  Google__Protobuf__Timestamp *timestamp;
  /*
   * Frame of reference for the image. The origin of the frame is the optical center of the camera. +x points to the right in the image, +y points down, and +z points into the plane of the image.
   */
  char *frame_id;
  /*
   * Compressed image data
   */
  ProtobufCBinaryData data;
  /*
   * Image format
   * 
   * Supported values: `jpeg`, `png`, `webp`, `avif`
   */
  char *format;
};
#define FOXGLOVE__COMPRESSED_IMAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foxglove__compressed_image__descriptor) \
, NULL, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string }


/* Foxglove__CompressedImage methods */
void   foxglove__compressed_image__init
                     (Foxglove__CompressedImage         *message);
size_t foxglove__compressed_image__get_packed_size
                     (const Foxglove__CompressedImage   *message);
size_t foxglove__compressed_image__pack
                     (const Foxglove__CompressedImage   *message,
                      uint8_t             *out);
size_t foxglove__compressed_image__pack_to_buffer
                     (const Foxglove__CompressedImage   *message,
                      ProtobufCBuffer     *buffer);
Foxglove__CompressedImage *
       foxglove__compressed_image__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foxglove__compressed_image__free_unpacked
                     (Foxglove__CompressedImage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foxglove__CompressedImage_Closure)
                 (const Foxglove__CompressedImage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foxglove__compressed_image__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foxglove_2fCompressedImage_2eproto__INCLUDED */
