/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/CompressedImage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/CompressedImage.pb-c.h"
void   foxglove__compressed_image__init
                     (Foxglove__CompressedImage         *message)
{
  static const Foxglove__CompressedImage init_value = FOXGLOVE__COMPRESSED_IMAGE__INIT;
  *message = init_value;
}
size_t foxglove__compressed_image__get_packed_size
                     (const Foxglove__CompressedImage *message)
{
  assert(message->base.descriptor == &foxglove__compressed_image__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__compressed_image__pack
                     (const Foxglove__CompressedImage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__compressed_image__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__compressed_image__pack_to_buffer
                     (const Foxglove__CompressedImage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__compressed_image__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__CompressedImage *
       foxglove__compressed_image__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__CompressedImage *)
     protobuf_c_message_unpack (&foxglove__compressed_image__descriptor,
                                allocator, len, data);
}
void   foxglove__compressed_image__free_unpacked
                     (Foxglove__CompressedImage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__compressed_image__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foxglove__compressed_image__field_descriptors[4] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__CompressedImage, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Foxglove__CompressedImage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "format",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foxglove__CompressedImage, format),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foxglove__CompressedImage, frame_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__compressed_image__field_indices_by_name[] = {
  1,   /* field[1] = data */
  2,   /* field[2] = format */
  3,   /* field[3] = frame_id */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange foxglove__compressed_image__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor foxglove__compressed_image__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.CompressedImage",
  "CompressedImage",
  "Foxglove__CompressedImage",
  "foxglove",
  sizeof(Foxglove__CompressedImage),
  4,
  foxglove__compressed_image__field_descriptors,
  foxglove__compressed_image__field_indices_by_name,
  1,  foxglove__compressed_image__number_ranges,
  (ProtobufCMessageInit) foxglove__compressed_image__init,
  NULL,NULL,NULL    /* reserved[123] */
};
