/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/LaserScan.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/LaserScan.pb-c.h"
void   foxglove__laser_scan__init
                     (Foxglove__LaserScan         *message)
{
  static const Foxglove__LaserScan init_value = FOXGLOVE__LASER_SCAN__INIT;
  *message = init_value;
}
size_t foxglove__laser_scan__get_packed_size
                     (const Foxglove__LaserScan *message)
{
  assert(message->base.descriptor == &foxglove__laser_scan__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__laser_scan__pack
                     (const Foxglove__LaserScan *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__laser_scan__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__laser_scan__pack_to_buffer
                     (const Foxglove__LaserScan *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__laser_scan__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__LaserScan *
       foxglove__laser_scan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__LaserScan *)
     protobuf_c_message_unpack (&foxglove__laser_scan__descriptor,
                                allocator, len, data);
}
void   foxglove__laser_scan__free_unpacked
                     (Foxglove__LaserScan *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__laser_scan__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foxglove__laser_scan__field_descriptors[7] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LaserScan, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LaserScan, frame_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LaserScan, pose),
    &foxglove__pose__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_angle",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LaserScan, start_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_angle",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LaserScan, end_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ranges",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Foxglove__LaserScan, n_ranges),
    offsetof(Foxglove__LaserScan, ranges),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intensities",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Foxglove__LaserScan, n_intensities),
    offsetof(Foxglove__LaserScan, intensities),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__laser_scan__field_indices_by_name[] = {
  4,   /* field[4] = end_angle */
  1,   /* field[1] = frame_id */
  6,   /* field[6] = intensities */
  2,   /* field[2] = pose */
  5,   /* field[5] = ranges */
  3,   /* field[3] = start_angle */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange foxglove__laser_scan__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor foxglove__laser_scan__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.LaserScan",
  "LaserScan",
  "Foxglove__LaserScan",
  "foxglove",
  sizeof(Foxglove__LaserScan),
  7,
  foxglove__laser_scan__field_descriptors,
  foxglove__laser_scan__field_indices_by_name,
  1,  foxglove__laser_scan__number_ranges,
  (ProtobufCMessageInit) foxglove__laser_scan__init,
  NULL,NULL,NULL    /* reserved[123] */
};
