/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/LaserScan.proto */

#ifndef PROTOBUF_C_foxglove_2fLaserScan_2eproto__INCLUDED
#define PROTOBUF_C_foxglove_2fLaserScan_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "foxglove/Pose.pb-c.h"
#include "google/protobuf/timestamp.pb-c.h"

typedef struct Foxglove__LaserScan Foxglove__LaserScan;


/* --- enums --- */


/* --- messages --- */

/*
 * A single scan from a planar laser range-finder
 */
struct  Foxglove__LaserScan
{
  ProtobufCMessage base;
  /*
   * Timestamp of scan
   */
  Google__Protobuf__Timestamp *timestamp;
  /*
   * Frame of reference
   */
  char *frame_id;
  /*
   * Origin of scan relative to frame of reference; points are positioned in the x-y plane relative to this origin; angles are interpreted as counterclockwise rotations around the z axis with 0 rad being in the +x direction
   */
  Foxglove__Pose *pose;
  /*
   * Bearing of first point, in radians
   */
  double start_angle;
  /*
   * Bearing of last point, in radians
   */
  double end_angle;
  /*
   * Distance of detections from origin; assumed to be at equally-spaced angles between `start_angle` and `end_angle`
   */
  size_t n_ranges;
  double *ranges;
  /*
   * Intensity of detections
   */
  size_t n_intensities;
  double *intensities;
};
#define FOXGLOVE__LASER_SCAN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foxglove__laser_scan__descriptor) \
, NULL, (char *)protobuf_c_empty_string, NULL, 0, 0, 0,NULL, 0,NULL }


/* Foxglove__LaserScan methods */
void   foxglove__laser_scan__init
                     (Foxglove__LaserScan         *message);
size_t foxglove__laser_scan__get_packed_size
                     (const Foxglove__LaserScan   *message);
size_t foxglove__laser_scan__pack
                     (const Foxglove__LaserScan   *message,
                      uint8_t             *out);
size_t foxglove__laser_scan__pack_to_buffer
                     (const Foxglove__LaserScan   *message,
                      ProtobufCBuffer     *buffer);
Foxglove__LaserScan *
       foxglove__laser_scan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foxglove__laser_scan__free_unpacked
                     (Foxglove__LaserScan *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foxglove__LaserScan_Closure)
                 (const Foxglove__LaserScan *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foxglove__laser_scan__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foxglove_2fLaserScan_2eproto__INCLUDED */
