/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/LocationFix.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/LocationFix.pb-c.h"
void   foxglove__location_fix__init
                     (Foxglove__LocationFix         *message)
{
  static const Foxglove__LocationFix init_value = FOXGLOVE__LOCATION_FIX__INIT;
  *message = init_value;
}
size_t foxglove__location_fix__get_packed_size
                     (const Foxglove__LocationFix *message)
{
  assert(message->base.descriptor == &foxglove__location_fix__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__location_fix__pack
                     (const Foxglove__LocationFix *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__location_fix__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__location_fix__pack_to_buffer
                     (const Foxglove__LocationFix *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__location_fix__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__LocationFix *
       foxglove__location_fix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__LocationFix *)
     protobuf_c_message_unpack (&foxglove__location_fix__descriptor,
                                allocator, len, data);
}
void   foxglove__location_fix__free_unpacked
                     (Foxglove__LocationFix *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__location_fix__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue foxglove__location_fix__position_covariance_type__enum_values_by_number[4] =
{
  { "UNKNOWN", "FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__UNKNOWN", 0 },
  { "APPROXIMATED", "FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__APPROXIMATED", 1 },
  { "DIAGONAL_KNOWN", "FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__DIAGONAL_KNOWN", 2 },
  { "KNOWN", "FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__KNOWN", 3 },
};
static const ProtobufCIntRange foxglove__location_fix__position_covariance_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex foxglove__location_fix__position_covariance_type__enum_values_by_name[4] =
{
  { "APPROXIMATED", 1 },
  { "DIAGONAL_KNOWN", 2 },
  { "KNOWN", 3 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor foxglove__location_fix__position_covariance_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "foxglove.LocationFix.PositionCovarianceType",
  "PositionCovarianceType",
  "Foxglove__LocationFix__PositionCovarianceType",
  "foxglove",
  4,
  foxglove__location_fix__position_covariance_type__enum_values_by_number,
  4,
  foxglove__location_fix__position_covariance_type__enum_values_by_name,
  1,
  foxglove__location_fix__position_covariance_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor foxglove__location_fix__field_descriptors[7] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LocationFix, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LocationFix, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LocationFix, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_covariance",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Foxglove__LocationFix, n_position_covariance),
    offsetof(Foxglove__LocationFix, position_covariance),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_covariance_type",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LocationFix, position_covariance_type),
    &foxglove__location_fix__position_covariance_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LocationFix, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foxglove__LocationFix, frame_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__location_fix__field_indices_by_name[] = {
  2,   /* field[2] = altitude */
  6,   /* field[6] = frame_id */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
  3,   /* field[3] = position_covariance */
  4,   /* field[4] = position_covariance_type */
  5,   /* field[5] = timestamp */
};
static const ProtobufCIntRange foxglove__location_fix__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor foxglove__location_fix__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.LocationFix",
  "LocationFix",
  "Foxglove__LocationFix",
  "foxglove",
  sizeof(Foxglove__LocationFix),
  7,
  foxglove__location_fix__field_descriptors,
  foxglove__location_fix__field_indices_by_name,
  1,  foxglove__location_fix__number_ranges,
  (ProtobufCMessageInit) foxglove__location_fix__init,
  NULL,NULL,NULL    /* reserved[123] */
};
