/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/LocationFix.proto */

#ifndef PROTOBUF_C_foxglove_2fLocationFix_2eproto__INCLUDED
#define PROTOBUF_C_foxglove_2fLocationFix_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"

typedef struct Foxglove__LocationFix Foxglove__LocationFix;


/* --- enums --- */

/*
 * Type of position covariance
 */
typedef enum _Foxglove__LocationFix__PositionCovarianceType {
  /*
   * Unknown position covariance type
   */
  FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__UNKNOWN = 0,
  /*
   * Position covariance is approximated
   */
  FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__APPROXIMATED = 1,
  /*
   * Position covariance is per-axis, so put it along the diagonal
   */
  FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__DIAGONAL_KNOWN = 2,
  /*
   * Position covariance of the fix is known
   */
  FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__KNOWN = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE)
} Foxglove__LocationFix__PositionCovarianceType;

/* --- messages --- */

/*
 * A navigation satellite fix for any Global Navigation Satellite System
 */
struct  Foxglove__LocationFix
{
  ProtobufCMessage base;
  /*
   * Timestamp of the message
   */
  Google__Protobuf__Timestamp *timestamp;
  /*
   * Frame for the sensor. Latitude and longitude readings are at the origin of the frame.
   */
  char *frame_id;
  /*
   * Latitude in degrees
   */
  double latitude;
  /*
   * Longitude in degrees
   */
  double longitude;
  /*
   * Altitude in meters
   */
  double altitude;
  /*
   * Position covariance (m^2) defined relative to a tangential plane through the reported position. The components are East, North, and Up (ENU), in row-major order.
   */
  /*
   * length 9
   */
  size_t n_position_covariance;
  double *position_covariance;
  /*
   * If `position_covariance` is available, `position_covariance_type` must be set to indicate the type of covariance.
   */
  Foxglove__LocationFix__PositionCovarianceType position_covariance_type;
};
#define FOXGLOVE__LOCATION_FIX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foxglove__location_fix__descriptor) \
, NULL, (char *)protobuf_c_empty_string, 0, 0, 0, 0,NULL, FOXGLOVE__LOCATION_FIX__POSITION_COVARIANCE_TYPE__UNKNOWN }


/* Foxglove__LocationFix methods */
void   foxglove__location_fix__init
                     (Foxglove__LocationFix         *message);
size_t foxglove__location_fix__get_packed_size
                     (const Foxglove__LocationFix   *message);
size_t foxglove__location_fix__pack
                     (const Foxglove__LocationFix   *message,
                      uint8_t             *out);
size_t foxglove__location_fix__pack_to_buffer
                     (const Foxglove__LocationFix   *message,
                      ProtobufCBuffer     *buffer);
Foxglove__LocationFix *
       foxglove__location_fix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foxglove__location_fix__free_unpacked
                     (Foxglove__LocationFix *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foxglove__LocationFix_Closure)
                 (const Foxglove__LocationFix *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foxglove__location_fix__descriptor;
extern const ProtobufCEnumDescriptor    foxglove__location_fix__position_covariance_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foxglove_2fLocationFix_2eproto__INCLUDED */
