/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/PackedElementField.proto */

#ifndef PROTOBUF_C_foxglove_2fPackedElementField_2eproto__INCLUDED
#define PROTOBUF_C_foxglove_2fPackedElementField_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Foxglove__PackedElementField Foxglove__PackedElementField;


/* --- enums --- */

/*
 * Numeric type
 */
typedef enum _Foxglove__PackedElementField__NumericType {
  /*
   * Unknown numeric type
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UNKNOWN = 0,
  /*
   * Unsigned 8-bit integer
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UINT8 = 1,
  /*
   * Signed 8-bit integer
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__INT8 = 2,
  /*
   * Unsigned 16-bit integer
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UINT16 = 3,
  /*
   * Signed 16-bit integer
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__INT16 = 4,
  /*
   * Unsigned 32-bit integer
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UINT32 = 5,
  /*
   * Signed 32-bit integer
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__INT32 = 6,
  /*
   * 32-bit floating-point number
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__FLOAT32 = 7,
  /*
   * 64-bit floating-point number
   */
  FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__FLOAT64 = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE)
} Foxglove__PackedElementField__NumericType;

/* --- messages --- */

/*
 * A field present within each element in a byte array of packed elements.
 */
struct  Foxglove__PackedElementField
{
  ProtobufCMessage base;
  /*
   * Name of the field
   */
  char *name;
  /*
   * Byte offset from start of data buffer
   */
  uint32_t offset;
  /*
   * Type of data in the field. Integers are stored using little-endian byte order.
   */
  Foxglove__PackedElementField__NumericType type;
};
#define FOXGLOVE__PACKED_ELEMENT_FIELD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foxglove__packed_element_field__descriptor) \
, (char *)protobuf_c_empty_string, 0, FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UNKNOWN }


/* Foxglove__PackedElementField methods */
void   foxglove__packed_element_field__init
                     (Foxglove__PackedElementField         *message);
size_t foxglove__packed_element_field__get_packed_size
                     (const Foxglove__PackedElementField   *message);
size_t foxglove__packed_element_field__pack
                     (const Foxglove__PackedElementField   *message,
                      uint8_t             *out);
size_t foxglove__packed_element_field__pack_to_buffer
                     (const Foxglove__PackedElementField   *message,
                      ProtobufCBuffer     *buffer);
Foxglove__PackedElementField *
       foxglove__packed_element_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foxglove__packed_element_field__free_unpacked
                     (Foxglove__PackedElementField *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foxglove__PackedElementField_Closure)
                 (const Foxglove__PackedElementField *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foxglove__packed_element_field__descriptor;
extern const ProtobufCEnumDescriptor    foxglove__packed_element_field__numeric_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foxglove_2fPackedElementField_2eproto__INCLUDED */
