/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/PackedElementField.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/PackedElementField.pb-c.h"
void   foxglove__packed_element_field__init
                     (Foxglove__PackedElementField         *message)
{
  static const Foxglove__PackedElementField init_value = FOXGLOVE__PACKED_ELEMENT_FIELD__INIT;
  *message = init_value;
}
size_t foxglove__packed_element_field__get_packed_size
                     (const Foxglove__PackedElementField *message)
{
  assert(message->base.descriptor == &foxglove__packed_element_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__packed_element_field__pack
                     (const Foxglove__PackedElementField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__packed_element_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__packed_element_field__pack_to_buffer
                     (const Foxglove__PackedElementField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__packed_element_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__PackedElementField *
       foxglove__packed_element_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__PackedElementField *)
     protobuf_c_message_unpack (&foxglove__packed_element_field__descriptor,
                                allocator, len, data);
}
void   foxglove__packed_element_field__free_unpacked
                     (Foxglove__PackedElementField *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__packed_element_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue foxglove__packed_element_field__numeric_type__enum_values_by_number[9] =
{
  { "UNKNOWN", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UNKNOWN", 0 },
  { "UINT8", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UINT8", 1 },
  { "INT8", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__INT8", 2 },
  { "UINT16", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UINT16", 3 },
  { "INT16", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__INT16", 4 },
  { "UINT32", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__UINT32", 5 },
  { "INT32", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__INT32", 6 },
  { "FLOAT32", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__FLOAT32", 7 },
  { "FLOAT64", "FOXGLOVE__PACKED_ELEMENT_FIELD__NUMERIC_TYPE__FLOAT64", 8 },
};
static const ProtobufCIntRange foxglove__packed_element_field__numeric_type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex foxglove__packed_element_field__numeric_type__enum_values_by_name[9] =
{
  { "FLOAT32", 7 },
  { "FLOAT64", 8 },
  { "INT16", 4 },
  { "INT32", 6 },
  { "INT8", 2 },
  { "UINT16", 3 },
  { "UINT32", 5 },
  { "UINT8", 1 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor foxglove__packed_element_field__numeric_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "foxglove.PackedElementField.NumericType",
  "NumericType",
  "Foxglove__PackedElementField__NumericType",
  "foxglove",
  9,
  foxglove__packed_element_field__numeric_type__enum_values_by_number,
  9,
  foxglove__packed_element_field__numeric_type__enum_values_by_name,
  1,
  foxglove__packed_element_field__numeric_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor foxglove__packed_element_field__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PackedElementField, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PackedElementField, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PackedElementField, type),
    &foxglove__packed_element_field__numeric_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__packed_element_field__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = offset */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange foxglove__packed_element_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor foxglove__packed_element_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.PackedElementField",
  "PackedElementField",
  "Foxglove__PackedElementField",
  "foxglove",
  sizeof(Foxglove__PackedElementField),
  3,
  foxglove__packed_element_field__field_descriptors,
  foxglove__packed_element_field__field_indices_by_name,
  1,  foxglove__packed_element_field__number_ranges,
  (ProtobufCMessageInit) foxglove__packed_element_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
