/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/PointCloud.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/PointCloud.pb-c.h"
void   foxglove__point_cloud__init
                     (Foxglove__PointCloud         *message)
{
  static const Foxglove__PointCloud init_value = FOXGLOVE__POINT_CLOUD__INIT;
  *message = init_value;
}
size_t foxglove__point_cloud__get_packed_size
                     (const Foxglove__PointCloud *message)
{
  assert(message->base.descriptor == &foxglove__point_cloud__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__point_cloud__pack
                     (const Foxglove__PointCloud *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__point_cloud__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__point_cloud__pack_to_buffer
                     (const Foxglove__PointCloud *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__point_cloud__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__PointCloud *
       foxglove__point_cloud__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__PointCloud *)
     protobuf_c_message_unpack (&foxglove__point_cloud__descriptor,
                                allocator, len, data);
}
void   foxglove__point_cloud__free_unpacked
                     (Foxglove__PointCloud *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__point_cloud__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foxglove__point_cloud__field_descriptors[6] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PointCloud, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PointCloud, frame_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PointCloud, pose),
    &foxglove__pose__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_stride",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PointCloud, point_stride),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fields",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Foxglove__PointCloud, n_fields),
    offsetof(Foxglove__PointCloud, fields),
    &foxglove__packed_element_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PointCloud, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__point_cloud__field_indices_by_name[] = {
  5,   /* field[5] = data */
  4,   /* field[4] = fields */
  1,   /* field[1] = frame_id */
  3,   /* field[3] = point_stride */
  2,   /* field[2] = pose */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange foxglove__point_cloud__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor foxglove__point_cloud__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.PointCloud",
  "PointCloud",
  "Foxglove__PointCloud",
  "foxglove",
  sizeof(Foxglove__PointCloud),
  6,
  foxglove__point_cloud__field_descriptors,
  foxglove__point_cloud__field_indices_by_name,
  1,  foxglove__point_cloud__number_ranges,
  (ProtobufCMessageInit) foxglove__point_cloud__init,
  NULL,NULL,NULL    /* reserved[123] */
};
