/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/Pose.proto */

#ifndef PROTOBUF_C_foxglove_2fPose_2eproto__INCLUDED
#define PROTOBUF_C_foxglove_2fPose_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "foxglove/Quaternion.pb-c.h"
#include "foxglove/Vector3.pb-c.h"

typedef struct Foxglove__Pose Foxglove__Pose;


/* --- enums --- */


/* --- messages --- */

/*
 * A position and orientation for an object or reference frame in 3D space
 */
struct  Foxglove__Pose
{
  ProtobufCMessage base;
  /*
   * Point denoting position in 3D space
   */
  Foxglove__Vector3 *position;
  /*
   * Quaternion denoting orientation in 3D space
   */
  Foxglove__Quaternion *orientation;
};
#define FOXGLOVE__POSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foxglove__pose__descriptor) \
, NULL, NULL }


/* Foxglove__Pose methods */
void   foxglove__pose__init
                     (Foxglove__Pose         *message);
size_t foxglove__pose__get_packed_size
                     (const Foxglove__Pose   *message);
size_t foxglove__pose__pack
                     (const Foxglove__Pose   *message,
                      uint8_t             *out);
size_t foxglove__pose__pack_to_buffer
                     (const Foxglove__Pose   *message,
                      ProtobufCBuffer     *buffer);
Foxglove__Pose *
       foxglove__pose__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foxglove__pose__free_unpacked
                     (Foxglove__Pose *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foxglove__Pose_Closure)
                 (const Foxglove__Pose *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foxglove__pose__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foxglove_2fPose_2eproto__INCLUDED */
