/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/Pose.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/Pose.pb-c.h"
void   foxglove__pose__init
                     (Foxglove__Pose         *message)
{
  static const Foxglove__Pose init_value = FOXGLOVE__POSE__INIT;
  *message = init_value;
}
size_t foxglove__pose__get_packed_size
                     (const Foxglove__Pose *message)
{
  assert(message->base.descriptor == &foxglove__pose__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__pose__pack
                     (const Foxglove__Pose *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__pose__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__pose__pack_to_buffer
                     (const Foxglove__Pose *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__pose__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__Pose *
       foxglove__pose__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__Pose *)
     protobuf_c_message_unpack (&foxglove__pose__descriptor,
                                allocator, len, data);
}
void   foxglove__pose__free_unpacked
                     (Foxglove__Pose *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__pose__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foxglove__pose__field_descriptors[2] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Pose, position),
    &foxglove__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orientation",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Pose, orientation),
    &foxglove__quaternion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__pose__field_indices_by_name[] = {
  1,   /* field[1] = orientation */
  0,   /* field[0] = position */
};
static const ProtobufCIntRange foxglove__pose__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foxglove__pose__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.Pose",
  "Pose",
  "Foxglove__Pose",
  "foxglove",
  sizeof(Foxglove__Pose),
  2,
  foxglove__pose__field_descriptors,
  foxglove__pose__field_indices_by_name,
  1,  foxglove__pose__number_ranges,
  (ProtobufCMessageInit) foxglove__pose__init,
  NULL,NULL,NULL    /* reserved[123] */
};
