/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/PosesInFrame.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/PosesInFrame.pb-c.h"
void   foxglove__poses_in_frame__init
                     (Foxglove__PosesInFrame         *message)
{
  static const Foxglove__PosesInFrame init_value = FOXGLOVE__POSES_IN_FRAME__INIT;
  *message = init_value;
}
size_t foxglove__poses_in_frame__get_packed_size
                     (const Foxglove__PosesInFrame *message)
{
  assert(message->base.descriptor == &foxglove__poses_in_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__poses_in_frame__pack
                     (const Foxglove__PosesInFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__poses_in_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__poses_in_frame__pack_to_buffer
                     (const Foxglove__PosesInFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__poses_in_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__PosesInFrame *
       foxglove__poses_in_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__PosesInFrame *)
     protobuf_c_message_unpack (&foxglove__poses_in_frame__descriptor,
                                allocator, len, data);
}
void   foxglove__poses_in_frame__free_unpacked
                     (Foxglove__PosesInFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__poses_in_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foxglove__poses_in_frame__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PosesInFrame, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foxglove__PosesInFrame, frame_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "poses",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Foxglove__PosesInFrame, n_poses),
    offsetof(Foxglove__PosesInFrame, poses),
    &foxglove__pose__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__poses_in_frame__field_indices_by_name[] = {
  1,   /* field[1] = frame_id */
  2,   /* field[2] = poses */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange foxglove__poses_in_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor foxglove__poses_in_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.PosesInFrame",
  "PosesInFrame",
  "Foxglove__PosesInFrame",
  "foxglove",
  sizeof(Foxglove__PosesInFrame),
  3,
  foxglove__poses_in_frame__field_descriptors,
  foxglove__poses_in_frame__field_indices_by_name,
  1,  foxglove__poses_in_frame__number_ranges,
  (ProtobufCMessageInit) foxglove__poses_in_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
