/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/Quaternion.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/Quaternion.pb-c.h"
void   foxglove__quaternion__init
                     (Foxglove__Quaternion         *message)
{
  static const Foxglove__Quaternion init_value = FOXGLOVE__QUATERNION__INIT;
  *message = init_value;
}
size_t foxglove__quaternion__get_packed_size
                     (const Foxglove__Quaternion *message)
{
  assert(message->base.descriptor == &foxglove__quaternion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__quaternion__pack
                     (const Foxglove__Quaternion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__quaternion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__quaternion__pack_to_buffer
                     (const Foxglove__Quaternion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__quaternion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__Quaternion *
       foxglove__quaternion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__Quaternion *)
     protobuf_c_message_unpack (&foxglove__quaternion__descriptor,
                                allocator, len, data);
}
void   foxglove__quaternion__free_unpacked
                     (Foxglove__Quaternion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__quaternion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foxglove__quaternion__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Quaternion, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Quaternion, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Quaternion, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Quaternion, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__quaternion__field_indices_by_name[] = {
  3,   /* field[3] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange foxglove__quaternion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor foxglove__quaternion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.Quaternion",
  "Quaternion",
  "Foxglove__Quaternion",
  "foxglove",
  sizeof(Foxglove__Quaternion),
  4,
  foxglove__quaternion__field_descriptors,
  foxglove__quaternion__field_indices_by_name,
  1,  foxglove__quaternion__number_ranges,
  (ProtobufCMessageInit) foxglove__quaternion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
