/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/Quaternion.proto */

#ifndef PROTOBUF_C_foxglove_2fQuaternion_2eproto__INCLUDED
#define PROTOBUF_C_foxglove_2fQuaternion_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Foxglove__Quaternion Foxglove__Quaternion;


/* --- enums --- */


/* --- messages --- */

/*
 * A [quaternion](https://eater.net/quaternions) representing a rotation in 3D space
 */
struct  Foxglove__Quaternion
{
  ProtobufCMessage base;
  /*
   * x value
   */
  double x;
  /*
   * y value
   */
  double y;
  /*
   * z value
   */
  double z;
  /*
   * w value
   */
  double w;
};
#define FOXGLOVE__QUATERNION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foxglove__quaternion__descriptor) \
, 0, 0, 0, 0 }


/* Foxglove__Quaternion methods */
void   foxglove__quaternion__init
                     (Foxglove__Quaternion         *message);
size_t foxglove__quaternion__get_packed_size
                     (const Foxglove__Quaternion   *message);
size_t foxglove__quaternion__pack
                     (const Foxglove__Quaternion   *message,
                      uint8_t             *out);
size_t foxglove__quaternion__pack_to_buffer
                     (const Foxglove__Quaternion   *message,
                      ProtobufCBuffer     *buffer);
Foxglove__Quaternion *
       foxglove__quaternion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foxglove__quaternion__free_unpacked
                     (Foxglove__Quaternion *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foxglove__Quaternion_Closure)
                 (const Foxglove__Quaternion *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foxglove__quaternion__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foxglove_2fQuaternion_2eproto__INCLUDED */
