/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/Vector3.proto */

#ifndef PROTOBUF_C_foxglove_2fVector3_2eproto__INCLUDED
#define PROTOBUF_C_foxglove_2fVector3_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Foxglove__Vector3 Foxglove__Vector3;


/* --- enums --- */


/* --- messages --- */

/*
 * A vector in 3D space that represents a direction only
 */
struct  Foxglove__Vector3
{
  ProtobufCMessage base;
  /*
   * x coordinate length
   */
  double x;
  /*
   * y coordinate length
   */
  double y;
  /*
   * z coordinate length
   */
  double z;
};
#define FOXGLOVE__VECTOR3__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foxglove__vector3__descriptor) \
, 0, 0, 0 }


/* Foxglove__Vector3 methods */
void   foxglove__vector3__init
                     (Foxglove__Vector3         *message);
size_t foxglove__vector3__get_packed_size
                     (const Foxglove__Vector3   *message);
size_t foxglove__vector3__pack
                     (const Foxglove__Vector3   *message,
                      uint8_t             *out);
size_t foxglove__vector3__pack_to_buffer
                     (const Foxglove__Vector3   *message,
                      ProtobufCBuffer     *buffer);
Foxglove__Vector3 *
       foxglove__vector3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foxglove__vector3__free_unpacked
                     (Foxglove__Vector3 *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foxglove__Vector3_Closure)
                 (const Foxglove__Vector3 *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foxglove__vector3__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foxglove_2fVector3_2eproto__INCLUDED */
