/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foxglove/Vector3.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foxglove/Vector3.pb-c.h"
void   foxglove__vector3__init
                     (Foxglove__Vector3         *message)
{
  static const Foxglove__Vector3 init_value = FOXGLOVE__VECTOR3__INIT;
  *message = init_value;
}
size_t foxglove__vector3__get_packed_size
                     (const Foxglove__Vector3 *message)
{
  assert(message->base.descriptor == &foxglove__vector3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foxglove__vector3__pack
                     (const Foxglove__Vector3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foxglove__vector3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foxglove__vector3__pack_to_buffer
                     (const Foxglove__Vector3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foxglove__vector3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foxglove__Vector3 *
       foxglove__vector3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foxglove__Vector3 *)
     protobuf_c_message_unpack (&foxglove__vector3__descriptor,
                                allocator, len, data);
}
void   foxglove__vector3__free_unpacked
                     (Foxglove__Vector3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foxglove__vector3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foxglove__vector3__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Vector3, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Vector3, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Foxglove__Vector3, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foxglove__vector3__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange foxglove__vector3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor foxglove__vector3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foxglove.Vector3",
  "Vector3",
  "Foxglove__Vector3",
  "foxglove",
  sizeof(Foxglove__Vector3),
  3,
  foxglove__vector3__field_descriptors,
  foxglove__vector3__field_indices_by_name,
  1,  foxglove__vector3__number_ranges,
  (ProtobufCMessageInit) foxglove__vector3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
